### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by razirafiq71** [Javanile/SchemaDB#14]
Hello Sir! I face an issue when I install this project via composer.kindly guide how to install it via composer

**Comment by francescobianco** [comment]
@razirafiq71 please show me an error report with message 
please commit code to me on this repo
https://github.com/javanile-hub/codeigniter-moldable-orm-samples/invitations

**Comment by razirafiq71** [comment]
kindly see attached file

**Comment by razirafiq71** [comment]
done
